export type Project = { name: string; icon: string; title: string; description: string; role: string; hue: string; image: string; alt: string };

export const projects: Project[] = [
  { name: "LOOM", icon: "✣", hue: "lavender", image: "/assets/loom.jpg", alt: "Loom AI writing companion mockup", title: "An AI writing companion that thinks alongside you, allowing you to capture ideas, edits, and drafts in one focused space.", description: "I designed Loom, a focused writing surface where ideas, edits, and drafts coexist without the chat clutter.", role: "Design Engineer, 2024" },
  { name: "Atlas Studio", icon: "@", hue: "peach", image: "/assets/atlas.png", alt: "Atlas Studio brand and product sprint mockup", title: "A two week brand and product sprint for a creative studio.", description: "End to end identity, marketing site, and a small product surface designed to feel quietly confident across every touchpoint.", role: "Product & Brand Designer, 2025" },
  { name: "Rhythm", icon: "⌁", hue: "violet", image: "/assets/rhythm.png", alt: "Rhythm calm analytics mockup", title: "Calm analytics for indie founders.", description: "A weekly digest that turns raw product data into a simple narrative. Built so you can read it on a Sunday with coffee.", role: "Founder & Designer, 2024" },
  { name: "Groove", icon: "♬", hue: "pink", image: "/assets/groove.png", alt: "Groove music school booking flow mockup", title: "Reimagining the booking flow for a music school, assisting thousands of students in finding the right lessons.", description: "I led a redesign of the lesson booking experience, cutting drop off in half and making the schedule feel like a calendar people actually want to open.", role: "Lead Designer, 2023" },
  { name: "Fieldnote", icon: "⌘", hue: "mint", image: "/assets/fieldnote.png", alt: "Fieldnote pocket sized research tool mockup", title: "A pocket sized research tool for design teams that want to get out of their docs and into the world.", description: "Capture quotes, tag patterns, and synthesize themes in one place. The interface stays out of the way so the thinking can happen.", role: "Design Engineer, 2024" },
  { name: "Talkback", icon: "◌", hue: "blue", image: "/assets/talkback.png", alt: "Talkback friendlier AI chat interface mockup", title: "A friendlier interface for talking to language models.", description: "An exploration of how AI chat could feel less like a terminal and more like a conversation with a curious friend.", role: "Independent Project, 2025" }
];
